# -*- coding: utf-8 -*-
"""SS-7-HPPM — Original Notebook Source

Originally generated by Google Colab.
Colab link: https://colab.research.google.com/drive/1-9Y4WSrNTpfbYxwb3e24pArZSIzlIdIs

NOTE: This file is preserved as the original reference.
For the modular, production-ready version, see:
  - model.py   (ML functions)
  - train.py   (training pipeline)
  - app.py     (Flask web app)
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from ipywidgets import Dropdown, FloatSlider , IntSlider , interact
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.metrics import mean_absolute_error
from sklearn.pipeline import make_pipeline

df=pd.read_csv("Bengaluru_House_Data.csv")

df.head()

df.info()

df["availability"].value_counts()

corr=df.select_dtypes("number").corr()
sns.heatmap(corr)

df.isnull().sum()

df1=df.drop(columns=["society","area_type","availability","balcony"])
df1

df1.info()

df1.dropna(inplace=True)

df1.isnull().sum()

df1['size'].unique()

df1['bedrooms']=df1['size'].apply(lambda x: int(x.split(" ")[0]))

df1.info()

df1=df1.drop(columns=["size"])

df1[df1.bedrooms>20]

df1['total_sqft'].unique()

def is_float(x):
  try:
    float(x)
  except:
    return False
  return True

df1[~df1['total_sqft'].apply(is_float)].head(10)

def convert_sqft_to_num(x):
    if isinstance(x, float):  # Check if x is already a float
        return x

    tokens = x.split('-')  # A token is a small unit obtained by splitting
    if len(tokens) == 2:
        return (float(tokens[0]) + float(tokens[1])) / 2

    try:
        return float(x)
    except:
        return None

df4 = df1.copy()  # Creating a separate copy of df1 to avoid modifying the original
df4['total_sqft'] = df4['total_sqft'].apply(convert_sqft_to_num)
df4.dropna(inplace=True)  # Removing rows where the conversion failed

df4.info()

plt.boxplot(df4['total_sqft'])

low, high = df4['total_sqft'].quantile([0.1, 0.9])
mask_area = df4['total_sqft'].between(low, high)
df4 = df4[mask_area]

plt.boxplot(df4['total_sqft'])

df4 = df1.copy()  # Creating a separate copy of df1 to avoid modifying the original
df4['total_sqft'] = df4['total_sqft'].apply(convert_sqft_to_num)
df4.dropna(inplace=True)  # Removing rows where the conversion failed

df4.info()

df4['total_sqft'].describe()

plt.boxplot(df4['bath'])

df4['bath'].describe()

df4['bath'].value_counts()

df4.head()

low, high = df4['total_sqft'].quantile([0.1, 0.9])
mask_area = df4['total_sqft'].between(low, high)
df4 = df4[mask_area]

df4['price_per_sqft'] = df4['price'] * 100000 / df4['total_sqft']
df4['price_per_sqft'].describe()

df4.location=df4.location.apply(lambda x: x.strip())
location_stats= df4['location'].value_counts(ascending=False)
location_stats

df4.location.nunique()

location_stats_less_than_10=location_stats[location_stats<=10]
len(location_stats_less_than_10)

df4.location=df4.location.apply(lambda x: 'other' if x in location_stats_less_than_10 else x)
len(df4.location.unique())

df4.head(10)

df4=df4.drop(columns='price_per_sqft')

# category_encoders is installed via: pip install -r requirements.txt

from category_encoders import OneHotEncoder

x=df4.drop(['price'], axis='columns')

y=df4.price

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2,random_state=10)

model=make_pipeline(OneHotEncoder(), LinearRegression())
model.fit(x_train,y_train)

y_pred=model.predict(x_test)
mae=mean_absolute_error(y_test,y_pred)
mae

from sklearn.metrics import mean_absolute_percentage_error as error

# calculating the average percentage difference between actual and predicted values
mae = error(y_test, y_pred)

mae

def predict_price(input_data: dict):
    input_df = pd.DataFrame([input_data])
    return model.predict(input_df)[0]

example_house = {
    'location': 'Bilaspur',
    'total_sqft': 1300,
    'bath': 3,
    'bedrooms': 3
}

print("Predicted Price:", predict_price(example_house))